server:
  port: 8081
spring:
  application:
    name: shopping-items-service
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf-8
    username: root
    password: ygb52338972
  rabbitmq:
      host: 192.168.138.202
      username: shopping
      password: 123456
      virtual-host: /shopping
      template:
        retry:
          enabled: true
          initial-interval: 10000ms
          max-interval: 300000ms
          multiplier: 2
        exchange: shopping.item.exchange
      publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5200/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}