server:
  port: 8084
spring:
  application:
      name: shopping-user-service
  datasource:
      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf-8
      username: root
      password: ygb52338972
  redis:
      host: 192.168.138.202
  rabbitmq:
    host: 192.168.138.202
    username: shopping
    password: 123456
    virtual-host: /shopping
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 210000ms
        multiplier: 2
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5200/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10