server:
  port: 8082
spring:
  application:
    name: shopping-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.138.202:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
      host: 192.168.138.202
      username: shopping
      password: 123456
      virtual-host: /shopping
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5200/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}