server:
  port: 8083
spring:
  thymeleaf:
    cache: false
  application:
    name: shopping-thymeleaf
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5200/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
shopping:
  thymeleaf:
    destPath: D:\softForInstall\nginx-1.12.2\html\item
